---
name: "within_b_d.timegapdiff"
description: "The allowed difference in years between the birth and death of an individual"
condition: "diff >= 0 && diff <= 110"
---
name: "within_b_d.consistencytolerance"
description: "The allowed difference in years between the registered age at death and the time gap between the registration of birth and death events"
condition: "diff < 2"
---
name: "within_b_m.timegapdiff"
description: "The allowed difference in years between the birth and marriage of an individual"
condition: "diff >= 14 && diff <= 80"
---
name: "between_b_d.timegapdiff"
description: "The allowed difference in years between the birth of an individual and the death of the parents"
condition: "diff >= -1 && diff <= 96"
---
name: "between_b_m.timegapdiff"
description: "The allowed difference in years between the birth of an individual and the marriage of the parents"
condition: "diff >= -5 && diff <= 36"
---
name: "between_d_m.timegapdiff"
description: "The allowed difference in years between the death of an individual and the marriage of the parents"
condition: "diff >= -5 && diff <= 146"
---
name: "between_m_m.timegapdiff"
description: "The allowed difference in years between the marriage of an individual and the marriage of the parents"
condition: "diff >= 14 && diff <= 100"
...
